services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: pushpay_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: pushpay_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  redis:
    image: redis:7.4-alpine
    container_name: pushpay_redis
    ports:
      - "6379:6379"
    
    volumes:
      - redis_data:/data
    networks:
      - pushpay-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_pass", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  redis_data:

networks:
  pushpay-network:
    driver: bridge